name: Add Label to run extended tests on approve

on:
  pull_request_review:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  label_issues:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: extended-tests
