name: After Approval

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests-after-approval:
    if: github.event.review.state == 'approved' && !contains(github.event.pull_request.labels.*.name, 'extended-tests')
    uses: ./.github/workflows/call-e2e-all-tests.yml

  integration-tests-after-approval:
    if: github.event.review.state == 'approved' && !contains(github.event.pull_request.labels.*.name, 'extended-tests')
    uses: ./.github/workflows/call-integration-tests.yml
