name: Lexical Tests (Extended)

on:
  pull_request:
    types: [labeled, synchronize, reopened]
    paths-ignore:
      - 'packages/lexical-website/**'
      - 'packages/*/README.md'
      - '.size-limit.js'
  pull_request_review:
    types: [submitted]

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip && github.event.review.state == 'commented' }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'always'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "merge_group"]'
  e2e-tests:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true' && ((github.repository_owner == 'facebook' && contains(github.event.pull_request.labels.*.name, 'extended-tests') && github.event.review.state != 'approved') || (github.event.review.state == 'commented' && !contains(github.event.pull_request.labels.*.name, 'extended-tests')))
    runs-on: ubuntu-latest
    steps:
      - name: Tesing workflow executed or skipped ${{needs.pre_job.outputs.should_skip}}
        run: |
          echo "Test executed ...  ${{needs.pre_job.outputs.should_skip}}"

  # integration-tests:
  #   needs: pre_job
  #   if: needs.pre_job.outputs.should_skip != true && (github.repository_owner == 'facebook' && contains(github.event.pull_request.labels.*.name, 'extended-tests') && github.event.review.state != 'approved') || (github.event.review.state == 'commented' && !contains(github.event.pull_request.labels.*.name, 'extended-tests'))
  #   run: |
