name: Lexical Tests (Extended)

on:
  workflow_call:
  pull_request:
    types: [labeled, synchronize]
    paths-ignore:
      - 'packages/lexical-website/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    if: contains(github.event.pull_request.labels.*.name, 'extended-tests')
    uses: ./.github/workflows/call-e2e-all-tests.yml
